# Analysis of Russian River Estuary Data

```{r include = FALSE}
require(rremat)
require(ggplot2)
require(knitr)
opts_chunk$set(fig.width = 12, fig.height = 8)
```

## Closure referencing

The code below adds a reference to CTD transect dates indicating the closure ID
associated with the transect and the number of days since the initiation of 
estuary closure.

```{r calc-days, echo = FALSE}
data(closures)
data(ctd)
closurecol = "closure.id"
durationcol = "days.since"
ctd[closurecol] = NA
ctd[durationcol] = NA
for(i in seq(nrow(closures))){
  idmask = ctd$date >= closures$initiation[i] & ctd$date <= closures$breach[i]
  ctd[idmask, closurecol] = closures$id[i]
  ctd[idmask, durationcol] = ctd[idmask, "date"] - closures$initiation[i]
}
```

## Analysis of surface data

```{r get-surface, echo = FALSE}
data(ctd.df)
require(dplyr)
surfdepth = 0.75
surf = summarize(group_by(ctd.df, date, dist), 
  ta = spline(depth, ta, xout = surfdepth)$y,
  sa = spline(depth, sa, xout = surfdepth)$y)
```


